<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions">
    <xsl:output method="text" indent="yes"/>
    <xsl:param name="logs"/>
    <xsl:variable name="logs-x" select="json-to-xml($logs)"/>
    <xsl:variable name="mapped-xml">
        <array xmlns="http://www.w3.org/2005/xpath-functions">
            <xsl:for-each select="$logs-x/fn:map/fn:array[@key='resourceLogs']/fn:map/fn:array[@key='scopeLogs']/fn:map/fn:array[@key='logRecords']/fn:map">
                <map>
                    <string key="type">log</string>
                    <string key="timeUnixNano">
                        <xsl:value-of select="fn:string[@key='timeUnixNano']"/>
                    </string>
                    <string key="observedTimeUnixNano">
                        <xsl:value-of select="fn:string[@key='observedTimeUnixNano']"/>
                    </string>
                    <string key="severityText">
                        <xsl:value-of select="fn:string[@key='severityText']"/>
                    </string>
                    <string key="message">
                        <xsl:value-of select="fn:map[@key='body']/fn:string[@key='stringValue']"/>
                        <xsl:for-each select="fn:array[@key='attributes']/fn:map">
                            <xsl:text>&#10;</xsl:text>
                            <xsl:value-of select="fn:string[@key='key']"/>
                            <xsl:text>: </xsl:text>
                            <xsl:value-of select="fn:map[@key='value']/fn:string[@key='stringValue']"/>
                        </xsl:for-each>
                    </string>
                    <string key="traceId">
                        <xsl:value-of select="fn:string[@key='traceId']"/>
                    </string>
                    <string key="spanId">
                        <xsl:value-of select="fn:string[@key='spanId']"/>
                    </string>
                </map>
            </xsl:for-each>
        </array>
    </xsl:variable>
    <xsl:template match="/">
        <xsl:value-of select="xml-to-json($mapped-xml)"/>
    </xsl:template>
</xsl:stylesheet>